### ISSUE TITLE
Understantindg the Binding

### ISSUE THREAD

**Issue by kigiri** [iostreamer-X/Awkward#9]
In an effort to reduce the amount of boilerplate needed to write code
I wanted to see if console automaticaly binded its method like it is on the recents version of chrome

this allow to do things like :

``` javascript
ls().map(el => el[0]).forEach(console.log)
```

but this result in a `TypeError: Cannot read property 'ui' of undefined`
so then when i tested with 

``` javascript
ls().map(el => el[0]).forEach(console.log.bind(console))
```

but this result in a `TypeError: Cannot read property 'log' of undefined`
lastly, for science purpose, i tested :

``` javascript
ls().map(el => el[0]).forEach(el => console.log.bind(console)(el))
```

Which also did fail resulting in the same error as above.

I would suggest to make lodash available and add some login sauce to it :

``` javascript
const _ = require('lodash')
_.mixin(_.reduce(console.prototype, (acc, key) => {
  acc[key] = console[key].bind(console)
  return acc
}, {})
```

Idealy one should be able to customise his scope with any utility he wants to use.

_Opinion : coffeescript don't drive me to contribute, but i really love the project_

**Comment by iostreamer-X** [comment]
Actually `console.log` is replaced by `awkward.log` while `eval`uating the expression, which is a vorpal ui function. And internally it refers to `this` to display arguments, and since `awkward.log` is being used inside `forEach` its `this` doesn't refer to the `awkward` object anymore. 

To fix this, `console.log` must be replaced with `awkward.log.bind(awkward)`, which is implemented in the newest commit and has been published on npm. Which means now one can do

``` js
ls().map(el => el[0]).forEach(console.log)
```

Please update your app.
Cheers!
